### ISSUE TITLE
Add an option to show both versions of the time for the tekufa

### ISSUE THREAD

**Issue by Elyahu41** [Elyahu41/royzmanimwebsite#24]
As mentioned in issue #15 , there should be an option/setting to allow the user to see both times for the tekufot I.E. according to the Ohr HaChaim calendar and according to the Amudei Horaah calendar. As mentioned before, the difference between these times is just 21 minutes. In the apps, if the user decides to see both of the times for the tekufot, I show both of the times as separate listings. However, what you could do is to merge the times and overlap them.

For example: Let's say that according to the Ohr Hachaim calendar, the tekufa happens at 9:30am. Then you would not be able to drink water from 9 - 10 am. The Amudei horaah calendar would subtract 21 minutes from both these times. So the tekufa would come out to 9:09am and you would not drink from 8:39 - 9:39 am.

You could show this as two separate listings if the user wants to see both, OR you could just merge them and put the earliest and latest time I.E. 8:39am - 10am.

I leave it up to you.

As mentioned in issue #15 , there should be an option/setting to allow the user to see both options for the tekufot.

**Comment by NightScript370** [comment]
There is no other listing on the platform that tries to be "Machmir" for both shita's, especially for something as insignificant as a prohibition of drinking water. The prohibition is only for plain water; not juice, not wine or any other liquid.

What I will implement, though, is a way to switch up the two. It is clear from every other calendar (Amudeh Hora'ah, Yalkut Yosef) that the way Ohr Hachaim does it is incorrect, and the answer of "minhag" is a cop-out. For the ability to represent the Yalkut Yosef calendar, I will implement the Amudeh Hora'ah calculation method into the Ohr Hachaim one. For code convenience's sake, I will also allow the inverse (but not because I believe in it).

**Comment by Elyahu41** [comment]
I wouldn't call it insignificant since Rabbi Ovadiah ZT"L went out of his way to say that it is a halacha that people should follow AND that every calendar should display the time.

Also, it is not clear if the other shita is incorrect. That is, in my opinion, taking it too far. Even if there are poskim that disagree with it, many people still follow the Ohr Hachaim calendar's time listing. I would assume even Rav Ovadiah ZT"L himself would follow that time instead of the way the Amudei Horaah calendar does it. Or maybe he followed both. We have no idea as of now.

Either way, whether or not you believe in it, it should be implemented imo.

P.S. that yalkut yosef calendar was not written by Rav Yitzchak Yosef so we don't know if he agrees to it. Even if his haskama is on it.
