### ISSUE TITLE
Ohr HaChaim calendar is not used in Israel by default

### ISSUE THREAD

**Issue by Elyahu41** [Elyahu41/royzmanimwebsite#28]
All rabbanim agree that the Ohr Hachaim calendar should be used in Israel. I just tested the website by putting in "Jerusalem" and it put me in Israel, however, it was still using the amudei horaah calendar. There needs to be a check in place to always set the calendar to ohr hachaim if the inIsrael boolean is true.

**Comment by NightScript370** [comment]
- Current branch: No implementation, purely determined by the selector on the bottom
- My current branch (v3.0): Implementation via if the name includes the word "Israel" (and from your commit, the word "Palestine" gets swapped over too because people don't understand how APIs work. I guess your commit was convenient for this check, though, so I won't necessarily revert it)
- Future work: Determine the area code of the geo location if it's the Israel ones. That will properly accommodate neighboring areas.
